expose:
  type: ingress
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: "wildcard-tls-secret"
  ingress:
    hosts:
      core: "harbor.k8s.labs.itmo.loc"
    className: "public"

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      storageClass: "microk8s-hostpath"
    chartmuseum:
      storageClass: "microk8s-hostpath"
    jobservice:
      storageClass: "microk8s-hostpath"
    database:
      storageClass: "microk8s-hostpath"
    redis:
      storageClass: "microk8s-hostpath"
    trivy:
      storageClass: "microk8s-hostpath"

harborAdminPassword: "pass123word"

externalURL: "https://harbor.k8s.labs.itmo.loc"

portal:
  nginx:
    config: |
      worker_processes auto;
      pid /tmp/nginx.pid;
      events {
          worker_connections  1024;
      }
      http {
          client_body_temp_path /tmp/client_body_temp;
          proxy_temp_path /tmp/proxy_temp;
          fastcgi_temp_path /tmp/fastcgi_temp;
          uwsgi_temp_path /tmp/uwsgi_temp;
          scgi_temp_path /tmp/scgi_temp;
          server {
              listen 8080;
              server_name  localhost;
              root   /usr/share/nginx/html;
              index  index.html index.htm;
              include /etc/nginx/mime.types;
              gzip on;
              gzip_min_length 1000;
              gzip_proxied expired no-cache no-store private auth;
              gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;
              location /devcenter-api-2.0 {
                  try_files $uri $uri/ /swagger-ui-index.html;
              }
              location / {
                  try_files $uri $uri/ /index.html;
              }
              location = /index.html {
                  add_header Cache-Control "no-store, no-cache, must-revalidate";
              }
          }
      }