replicaCount: 1

image:
  repository: harbor.k8s.labs.itmo.loc/public/wine-service
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  nodePort: null

ingress:
  enabled: true
  className: "public"
  hosts:
    - host: wine.k8s.labs.itmo.loc
      paths:
        - path: /
          pathType: Prefix

# spring:
#   config:
#     import: "optional:configmap:{{ .Chart.Name }}-config"

# Сервисы зависимостей
#dependencies:
#  redis:
#    enabled: true
#    serviceName: "redis-service"
#    port: 6379

#  qdrant:
#    enabled: true
#    serviceName: "qdrant-service"
#    restPort: 6333
#    grpcPort: 6334
dependencies:
  redis:
    serviceName: "my-redis-master"
  qdrant:
    serviceName: "my-qdrant"

# Переменные окружения
env:
  APP_PORT: 8080
  SPRING_PROFILES_ACTIVE: "docker"
  HF_TOKEN: ""  # будет установлен через Secret

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

# Persistence для Qdrant
#persistence:
#  enabled: true
#  storageClass: "microk8s-hostpath"
#  size: "5Gi"
